paths:
  adsp: hexagon-dsp-binaries/sa8775p/Qualcomm/SA8775P-RIDE/adsp-DSP.AT.1.0.1-00079.2-LEMANS-1
  cdsp: hexagon-dsp-binaries/sa8775p/Qualcomm/SA8775P-RIDE/cdsp-DSP.AT.1.0.1-00079.2-LEMANS-1
  cdsp1: hexagon-dsp-binaries/sa8775p/Qualcomm/SA8775P-RIDE/cdsp1-DSP.AT.1.0.1-00079.2-LEMANS-1
  gdsp0: hexagon-dsp-binaries/sa8775p/Qualcomm/SA8775P-RIDE/gdsp0-DSP.AT.1.0.1-00079.2-LEMANS-1
  gdsp1: hexagon-dsp-binaries/sa8775p/Qualcomm/SA8775P-RIDE/gdsp1-DSP.AT.1.0.1-00079.2-LEMANS-1
  firmware: linux-firmware/qcom/sa8775p
